### ISSUE TITLE
`supports managed_home` broken in Chef 13

### ISSUE THREAD

**Issue by skylerto** [tacitknowledge/aem-cookbook#67]
```
-----> Converging <publish-centos-72>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.6.4...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (always install latest version)
       Downloading https://omnitruck.chef.io/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       el 7 x86_64
       Getting information for chef stable  for el...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=el&pv=7&m=x86_64
         to file /tmp/install.sh.22751/metadata.txt
       trying wget...
       sha1	65c046c91a7186a28af9642e3cffcd72296cf602
       sha256	b8397ea2a33a3f4c860daac1cb0714a11d8dad5287b0eb7054e8432d484f9f2c
       url	https://packages.chef.io/files/stable/chef/13.1.31/el/7/chef-13.1.31-1.el7.x86_64.rpm
       version	13.1.31
       downloaded metadata file looks valid...
       /tmp/omnibus/cache/chef-13.1.31-1.el7.x86_64.rpm already exists, verifiying checksum...
       Comparing checksum with sha256sum...
       checksum compare succeeded, using existing file!
       
       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
       
       You are installing an omnibus package without a version pin.  If you are installing
       on production servers via an automated process this is DANGEROUS and you will
       be upgraded without warning on new releases, even to new major releases.
       Letting the version float is only appropriate in desktop, test, development or
       CI/CD environments.
       
       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
       
       Installing chef 
       installing with rpm...
       warning: /tmp/omnibus/cache/chef-13.1.31-1.el7.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
       Preparing...                          ################################# [100%]
       Updating / installing...
          1:chef-13.1.31-1.el7               ################################# [100%]
       Thank you for installing Chef!
       Transferring files to <publish-centos-72>
       Starting Chef Client, version 13.1.31
       resolving cookbooks for run list: ["inlet_aem::publish"]
       Synchronizing Cookbooks:
         - aem (2.2.0)
         - apache2 (3.3.0)
         - ark (0.8.2)
         - iptables (4.2.0)
         - java (1.50.0)
         - apt (6.1.2)
         - windows (3.1.1)
         - homebrew (4.2.0)
         - ohai (5.1.0)
         - inlet_aem (1.0.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       /tmp/kitchen/cache/cookbooks/ark/resources/default.rb:32: warning: constant ::Fixnum is deprecated
       /tmp/kitchen/cache/cookbooks/ark/resources/default.rb:43: warning: constant ::Fixnum is deprecated
       Recipe: aem::_base_aem_setup
         * yum_package[libcurl-devel] action install (up to date)
         * yum_package[gcc] action install (up to date)
         * chef_gem[curb] action install (up to date)
         
         ================================================================================
         Recipe Compile Error in /tmp/kitchen/cache/cookbooks/inlet_aem/recipes/publish.rb
         ================================================================================
         
         NoMethodError
         -------------
         undefined method `supports' for Chef::Resource::User::LinuxUser
         
         Cookbook Trace:
         ---------------
           /tmp/kitchen/cache/cookbooks/aem/recipes/_base_aem_setup.rb:62:in `block in from_file'
           /tmp/kitchen/cache/cookbooks/aem/recipes/_base_aem_setup.rb:57:in `from_file'
           /tmp/kitchen/cache/cookbooks/aem/recipes/publish.rb:19:in `from_file'
           /tmp/kitchen/cache/cookbooks/inlet_aem/recipes/publish.rb:11:in `from_file'
         
         Relevant File Content:
         ----------------------
         /tmp/kitchen/cache/cookbooks/aem/recipes/_base_aem_setup.rb:
         
          55:    end
          56:  else
          57:    user 'crx' do
          58:      comment 'crx/aem role user'
          59:      system true
          60:      shell '/bin/bash'
          61:      home '/home/crx'
          62>>     supports manage_home: true
          63:      action :create
          64:    end
          65:  end
          66:  
          67:  directory '/home/crx/.ssh' do
          68:    owner 'crx'
          69:    group 'crx'
          70:    mode 0700
          71:  end
         
         System Info:
         ------------
         chef_version=13.1.31
         platform=centos
         platform_version=7.2.1511
         ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
         program_name=chef-client worker: ppid=22873;start=13:34:59;
         executable=/opt/chef/bin/chef-client
         
         
         Running handlers:
       [2017-06-30T13:35:02+00:00] ERROR: Running exception handlers
       [2017-06-30T13:35:02+00:00] ERROR: Running exception handlers
         Running handlers complete
       [2017-06-30T13:35:02+00:00] ERROR: Exception handlers complete
       [2017-06-30T13:35:02+00:00] ERROR: Exception handlers complete
         Chef Client failed. 0 resources updated in 03 seconds
       [2017-06-30T13:35:02+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-06-30T13:35:02+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-06-30T13:35:02+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-06-30T13:35:02+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-06-30T13:35:02+00:00] ERROR: undefined method `supports' for Chef::Resource::User::LinuxUser
       [2017-06-30T13:35:02+00:00] ERROR: undefined method `supports' for Chef::Resource::User::LinuxUser
       [2017-06-30T13:35:02+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
       [2017-06-30T13:35:02+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

#64 fixes this.

**Comment by skylerto** [comment]
Part of a, now general PR: #70
